### ISSUE TITLE
Add citation and metadata for example  information

### ISSUE THREAD

**Issue by tombishop1** [tombishop1/itraxBook#1]
#c0217ec has added the example data @miros-c has provided and made it available. @miros-c I've found the following from the cruise report, but could you provide a data citation and perhaps a summary description of the core, scan parameters etc? If you put them here, I'll integrate them into a paragraph in the book. Then, all (most?) of the examples in this book will be based on these data.

> Station CD16619-01 was reached at 1020 hrs and was aimed at an area of reduced 3.5kHz penetration ~3 km to the north of the channel. Water depth was 4467 m. A single 6 m barrel was used at this site in an attempt to overcome the problem of inverted core catchers, which appeared to be the result of particularly stiff ooze layers. The corer was in the water at 1034 hrs and reached the seabed at 1157 hrs, showing a pullout of 6.3 tonnes (31d30.794’N/17d11.777’W). It returned on deck at 1320 hrs and contained a 4.3 m core with a series of volcanic ‘bypass’ turbidites. The core catcher was undamaged on this deployment.
> Southampton Oceanography Centre Cruise Report, No. 59, 31pp.

**Comment by miros-c** [comment]
Piston core CD166/19 was recovered from the Agadir Basin during the RRS Charles Darwin expedition CD166 in 2004 (Wynn and Cronin, 2005). The core site is located at 31°31’ N, 17°11.77’ W at a water depth of 4502 m. The coring operation recovered 4.3 m of sediment composed of hemipelagite and turbidites. The hemipelagic sediments range from cream-brown carbonate-rich marl/ooze to red-brown clays. The turbidites include siliciclastic, volcaniclastic and calcareous sediments.

The split core sections were analysed using the Cox Analytical Systems Itrax core scanner at the British Ocean Sediment Core Research Facility, National Oceanography Centre (Southampton, UK). The split core surfaces were cleaned and loaded to the core scanner along with a radiographic reference sample (Francus et al., 2015) and a colour card. The cores were first scanned to measure the sample surface height and to obtain optical images. The core sections were then covered with Mylar film to reduce sample desiccation during XRF scanning and x-radiography. 

XRF data were acquired using a molybdenum X-ray tube set at 30 kV and 30 mA with a dwell time of 30 seconds and a step size of 1 mm. X-radiographs were acquired with voltage and current set to 55 kV and 50 mA, respectively, and dwell time set to 500 ms. Step size for the x-radiography was set to 200 µm. Two replicate XRF scans were also performed for each of the three core sections that make up this core.  The XRF settings for the replicates were kept consistent with those of the main XRF scan. The interval selected for the replicate scans ranged from 10 cm to 15 cm of the the total sample length. All raw XRF raw data were reprocessed using the QSpec spectral analysis software to optimise peak fitting.

References
Wynn R., Cronin B. (2005) RRS “Charles Darwin” Cruise CD166, 29 Oct–22 Nov (2004) Sedimentary processes and deposits in the Agadir Basin and Gulf of Cadiz. Southampton Oceanography Centre Cruise Report, 59, 13.

Francus P., Kanamaru K., Fortin D., (2015) Chapter 20: Standardization and Calibration of X-Radiographs Acquired with the ITRAX Core Scanner, In I.W. Croudace, R.G. Rothwell (Eds.), Micro-XRF Studies of Sediment Cores, Developments in Paleoenvironmental Research 17, Springer, Dordrecht (2015)

**Comment by tombishop1** [comment]
Closed with faf334f

**Comment by tombishop1** [comment]
Closed with faf334f
